{{- if and .Values.registryAuth.configJson (not .Values.registryAuth.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "java-task-consumer.fullname" . }}-registry-auth
  labels:
    {{- include "java-task-consumer.labels" . | nindent 4 }}
type: Opaque
stringData:
  config.json: |
{{ .Values.registryAuth.configJson | indent 4 }}
{{- end }}
