{{- if .Values.apihub.accessToken }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "java-task-consumer.fullname" . }}-api-key
  labels:
    {{- include "java-task-consumer.labels" . | nindent 4 }}
type: Opaque
stringData:
  access_token: {{ .Values.apihub.accessToken | quote }}
{{- end }}
