apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "java-task-consumer.fullname" . }}
  labels:
    {{- include "java-task-consumer.labels" . | nindent 4 }}
automountServiceAccountToken: false
